language: node_js

services:
    - 'docker'

node_js:
    - "10"
    - "12"

cache:
    directories:
        - "node_modules"

after_success:
    - docker build -t nestjs-products-api .
    - docker tag nestjs-products-api:latest $DOCKER_USERNAME/nestjs-products-api:latest
    - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ;
        docker push $DOCKER_USERNAME/nestjs-products-api:latest ;
      fi

notifications:
    email: false