language: node_js

services:
    - 'docker'

node_js:
    - "10"
    - "12"

cache:
    directories:
        - "node_modules"

after_success:
    - docker build -t nestjs-products-api .

before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login --user "$DOCKER_USERNAME" --password-stdin ;
    - docker tag nestjs-products-api $DOCKER_USERNAME/nestjs-products-api:latest

deploy:
    provide: script
    script: docker push $DOCKER_USERNAME/nestjs-products-api:latest ;

notifications:
    email: false